# Generated by Django 3.2.6 on 2021-08-11 15:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgid', models.CharField(max_length=25)),
                ('Name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('cost', models.CharField(max_length=6)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('photo', models.ImageField(upload_to='media/preview')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webpages.stays')),
            ],
        ),
    ]
