# Generated by Django 3.2.6 on 2021-08-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_remove_stays_pgid'),
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('stay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.stays')),
            ],
        ),
        migrations.CreateModel(
            name='StayDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullAddress', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.owner')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.stays')),
            ],
        ),
    ]
