# Generated by Django 3.2.6 on 2021-08-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_auto_20210821_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
