# Generated by Django 3.2.6 on 2021-08-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_alter_stays_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedCard',
        ),
    ]
