# Generated by Django 3.2.6 on 2021-08-22 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_delete_featuredcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='stay',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpages.stays'),
        ),
    ]
