# Generated by Django 3.2.6 on 2021-08-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_alter_tenant_stay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stays',
            old_name='Name',
            new_name='name',
        ),
    ]
